// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

console.log("Loading controllers...")

import ColorPickerController from "./color_picker_controller"
application.register("color-picker", ColorPickerController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import FileUploadController from "./file_upload_controller"
application.register("file-upload", FileUploadController)

console.log("Controllers loaded successfully!")

// No controllers currently registered
