
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: paper_vault_rails_development
  username: postgres
  password: metasploit
  host: localhost
  port: 5432

test:
  <<: *default
  database: paper_vault_rails_test
  username: postgres
  password: metasploit
  host: localhost
  port: 5432
# As with config/credentials.yml, you never want to store sensitive information,
# like your database password, in your source code. If your source code is
# ever seen by anyone, they now have access to your database.
#
# Instead, provide the password or a full connection URL as an environment
# variable when you boot the app. For example:
#
#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
#
# If the connection URL is provided in the special DATABASE_URL environment
# variable, Rails will automatically merge its configuration values on top of
# the values provided in this file. Alternatively, you can specify a connection
# URL environment variable explicitly:
#
#   production:
#     url: <%= ENV["MY_APP_DATABASE_URL"] %>
#
# Read https://guides.rubyonrails.org/configuring.html#configuring-a-database
# for a full overview on how database connection configuration can be specified.
#
production:
  primary: &primary_production
    <<: *default
    database: paper_vault_rails_production
    username: paper_vault_rails
    password: <%= ENV["PAPER_VAULT_RAILS_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: paper_vault_rails_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: paper_vault_rails_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: paper_vault_rails_production_cable
    migrations_paths: db/cable_migrate
